name: Flutter Setup
description: Checkout repo and set up Flutter

runs:
  using: composite
  steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          cache: true
          
      - name: Install dependencies
        run: flutter pub get
